repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # list of definitions and supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace # removes any whitespace at the ends of lines
      - id: check-yaml # check yaml syntax by loading all yaml files
      - id: debug-statements # check for python debug statements (import pdb, breakpoint, etc.)
      - id: detect-private-key # checks for private keys (BEGIN X PRIVATE KEY, etc.)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format